name: LINTER

on:
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v4.8.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main

          LINTERN_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_HTML: false
          VALIDATE_MARKDOWN: false
